FindWinNode     proto :DWORD
GetWinHeight    proto :DWORD
GetWinProc      proto :DWORD
GetWinAlpha     proto :DWORD
GetWinTray      proto :DWORD
SetWinHeight    proto :DWORD, :DWORD
SetWinProc      proto :DWORD, :DWORD
SetWinAlpha     proto :DWORD, :DWORD
SetWinTray      proto :DWORD, :DWORD
RemoveWinHeight proto :DWORD
RemoveWinProc   proto :DWORD
RemoveWinAlpha  proto :DWORD
RemoveWinTray   proto :DWORD
