WR_Start          proto
WR_Stop           proto
WR_RollupAll      proto
WR_UnrollAll      proto
WR_InvertRollAll  proto
WR_ToTrayAll      proto
WR_FromTrayAll    proto
WR_ToAlphaAll     proto
WR_FromAlphaAll   proto
WR_InvertAlphaAll proto
WR_SetConfig      proto :DWORD
WR_Rollup         proto :DWORD
WR_Unroll         proto :DWORD
WR_InvertRoll     proto :DWORD
WR_ToBack         proto :DWORD
WR_OnTop          proto :DWORD
WR_ToTray         proto :DWORD
WR_FromTray       proto :DWORD
WR_ToAlpha        proto :DWORD
WR_FromAlpha      proto :DWORD
WR_InvertAlpha    proto :DWORD
